### ISSUE TITLE
Mouse offset in the horizontal direction when using three-finger drag

### ISSUE THREAD

**Issue by dougzhi** [ClementGre/ThreeFingerDragOnWindows#33]
水平方向三指拖拽时，鼠标偶尔会划出去一段距离，而在垂直方向上不会出现类似的问题
[2023-11-30 22-34-20.zip](https://github.com/ClementGre/ThreeFingersDragOnWindows/files/13514076/2023-11-30.22-34-20.zip)
这里是我录制的一段拖拽时异常的视频

---
When dragging with three fingers in the horizontal direction, the mouse will occasionally move out a certain distance, but similar problems will not occur in the vertical direction.

Here is a video I recorded of something abnormal when dragging

**Comment by gocat** [comment]
我也有这个问题，你试试：

1. 先用一个手指滑动鼠标（不抬起
2. 然后放上另外两个手指拖动，就不会突然滑行很远了！

希望开发者能完善这个问题 : )

**Comment by dougzhi** [comment]
嗯，确实可行
滑动太快就会出现上面的问题

**Comment by ClementGre** [comment]
Hi, I published a new release that allows to record the app logs and to save the log file.
Can you update TFDOW and enable the logging, try to do a three-fingers drag reproducing the issue, stop the logging, and upload the file here?

Download the v2.0.2 [here](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.2) or on the [Microsoft Store](https://apps.microsoft.com/detail/9msx91wqcm2v?hl=fr-FR&gl=FR).

**Comment by dougzhi** [comment]
> Hi, I published a new release that allows to record the app logs and to save the log file. Can you update TFDOW and enable the logging, try to do a three-fingers drag reproducing the issue, stop the logging, and upload the file here?
> 
> Download the v2.0.2 [here](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.2) or on the [Microsoft Store](https://apps.microsoft.com/detail/9msx91wqcm2v?hl=fr-FR&gl=FR).

Great, this bug has been improved in the new version, thank you very much
