### ISSUE TITLE
start up minimize option

### ISSUE THREAD

**Issue by kwonyoong** [ClementGre/ThreeFingerDragOnWindows#41]
thanks for your awesome app.
I hope this app includes start up minimize option.

**Comment by ClementGre** [comment]
Hi, the app should not show up when booting up, it should start as minimized in the tray. Do you experience an anormal behavior?

**Comment by kwonyoong** [comment]
Yes. everytime I reboot or power up windows, the settings window is poped up.

----------------------------
I deleted windows stores version, and installed x64 version.
The problem is solved!

**Comment by ClementGre** [comment]
Hi, this might be due to the app not being able to save its settings correctly. When using the Windows Store version, does the app settings are persistent after reboot?

**Comment by ClementGre** [comment]
Hi, I published a new release that allows to record the app logs and to save the log file from the Other settings pane.
Can you update TFDOW to the new Microsoft Store version, and enable the logging. Then after restarting your computer, download the log file and upload it here. Then I will be able to debug and see why is the settings window opening.

Download the v2.0.2 [here](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.2) or on the [Microsoft Store](https://apps.microsoft.com/detail/9msx91wqcm2v?hl=fr-FR&gl=FR).

**Comment by kwonyoong** [comment]
Hi, I installed v.2.0.2 MS Store version, and now the setting window is not showing up when I boot up. Maybe the problem is solved?
Anyway, I tried to download the log file. but, I don't know the location of the log file.
(When I click "Save log file" the app shuts off)
If you let me know the location of log file, I'll upload it!

For now, I'm using your app without any problem!
You are the one who makes me able to use Windows with touchpad like Mac. Thank you for such a great app!

**Comment by ClementGre** [comment]
Hi, there is no log file. The logs are recorded internally, and can be saved in a file with the "Save log file" button that should open a file saving dialog, but it makes the app crash for you, I don't know why...

It is possible that the latest version fixed your bug as I changed some things in the way settings are saved. I will close this issue as resolved for now. Thank's.
