### ISSUE TITLE
Automatically exit when the computer sleeps

### ISSUE THREAD

**Issue by renfan2021** [ClementGre/ThreeFingerDragOnWindows#43]
My system version is Win11 23H2. I found that sometimes, when my computer is turned on after sleeping, the program will automatically exit. This problem does not occur 100% of the time, but the frequency is not low.

**Comment by ClementGre** [comment]
Hi, do you use the Microsoft Store version or the GitHub one?
If you are using the Microsoft Store version, can you try to install the app from GitHub and see if the bug still occurs?

**Comment by ClementGre** [comment]
@libxzr provided a fix for this issue that I just released today in the v2.0.3. It should fix the issue you are having.

Download the v2.0.3 [here](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.3) or on the [Microsoft Store](https://apps.microsoft.com/detail/9msx91wqcm2v).
