### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by Sotatek-HuyTran9** [ClementGre/ThreeFingerDragOnWindows#44]
I disabled the "Tap twice and drag to multi-select" option, and enable the "Enable three fingers drag" in the app, but it's not working. 

Please help to support, thank you
![image](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/145948673/d479dc5a-841f-4809-b258-57dc9c74cb46)
![image](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/145948673/5ade3e70-ab63-4490-ad63-7f5fde21719d)

**Comment by Sotatek-HuyTran9** [comment]
![image](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/145948673/44defc3d-2b0a-4904-bd4d-1941101d7581)

**Comment by ClementGre** [comment]
Hi, do you see "Touchpad exists and is registered" on the app?
Do you see the fingers coordinates appearing on the app like on the readme:
![https://raw.githubusercontent.com/ClementGre/ThreeFingersDragOnWindows/main/ThreeFingersDragOnWindows/Assets/Screenshot-1.png](https://raw.githubusercontent.com/ClementGre/ThreeFingersDragOnWindows/main/ThreeFingersDragOnWindows/Assets/Screenshot-1.png)

What is your displayed event speed?

Also, can you check that in the Three Fingers Drag, the "Enable three fingers mouse move" option is enabled?

**Comment by Sotatek-HuyTran9** [comment]
![image](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/145948673/ae259f55-4347-437f-879d-fa4efa2cb3a2)
Touchpad: Registered 
Event speed: 6ms
Enable three fingers mouse move: Enabled

Please help to resolved :)

**Comment by VictorFlores00** [comment]
same problem here :/

**Comment by ClementGre** [comment]
Hi, I published a new release that allows to record the app logs and to save the log file from the Other settings pane.
Can you update TFDOW and enable the logging, restart the app, try to do a three-fingers drag, stop the logging, and upload the file here?

Download the v2.0.2 [here](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.2) or on the [Microsoft Store](https://apps.microsoft.com/detail/9msx91wqcm2v?hl=fr-FR&gl=FR).

**Comment by Sotatek-HuyTran9** [comment]
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/ClementGre/ThreeFingerDragOnWindows/files/14754083/Logs_ThreeFingerDragOnWindows.txt)
This is the log file

**Comment by ClementGre** [comment]
Looks like your touchpad reports an empty touchpad contacts list half the time. I can try to fix that issue by ignoring the empty touchpad contacts reports.
I couldn't identify any three fingers drag on the log file. The log size is limited to 10,000 lines, can you try again to record logs just trying a single three finger drag, and stopping the logging right after.
Can you also tell me what CPU architecture you have so I'll be able to build a custom version for you, trying if the bug can be fixed.

**Comment by Sotatek-HuyTran9** [comment]
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/ClementGre/ThreeFingerDragOnWindows/files/14755874/Logs_ThreeFingerDragOnWindows.txt)
Here you go 
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/145948673/36af34db-2d15-4bed-a52c-c3d2285ff1fd)
Please lemme know if I missed anything

**Comment by ClementGre** [comment]
Thank's, it is strange as there is no persistent report for three fingers at the same time, even removing the empty reports. I will make a new build for you soon, but the bug is most likely due to the library [emoacht/RawInput.Touchpad](https://github.com/emoacht/RawInput.Touchpad) that I am using.

**Comment by bigdou-x** [comment]
version v2.0.5.0
The current version still has this issue
[Uploading Logs_ThreeFingerDragOnWindows.txt…]()

**Comment by ClementGre** [comment]
You sent the message too fast, the log file you were trying to upload hasn't had the time to upload. Can you send it again?

**Comment by bigdou-x** [comment]
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/user-attachments/files/16385813/Logs_ThreeFingerDragOnWindows.txt)

**Comment by kit-zeason** [comment]
I fully understand that many new versions may not be as stable. However, is it possible to implement a feature that allows us to disable automatic updates? This would enable us to adhere to a stable version and avoid disruptions to our familiar workflow.

**Comment by ClementGre** [comment]
Hi @kit-zeason,
You can install ThreeFingersDragOnWindows from GitHub releases if you do not want to have automatic updates.

**Comment by ClementGre** [comment]
@bigdou-x, your logs files reveals the same issue as in #63 and #66: the raw hid reports correctly a contact count of three, but there is actually only one contact information available.
I will try to fix this soon.

**Comment by bigdou-x** [comment]
Okay, thank you for your hard work

**Comment by ClementGre** [comment]
The v2.0.5 indeed broke the TFD for the touchpads that send each contact as individual raw hid reports.

I fixed the bug and tried to make a new parsing algorithm that should work with all touchpads, even if I can’t test it.
The v2.0.6 is on its way to being certified by the Microsoft Store!

**Comment by ClementGre** [comment]
I just released v2.0.6. It should fix this issue. Can you try it out?
See [v2.0.6](https://github.com/ClementGre/ThreeFingerDragOnWindows/releases/tag/2.0.6) | [MS Store](https://apps.microsoft.com/detail/9MSX91WQCM2V?)

**Comment by bigdou-x** [comment]
I verified it, it's solved.
