### ISSUE TITLE
Thanks for your product, great solution to the windows trackpad dragging problem! I have some new ideas.

### ISSUE THREAD

**Issue by 2956694624** [ClementGre/ThreeFingerDragOnWindows#51]
1. windows provides a touchpad sensitivity area control method, currently achieved through the registry, but the interface is not friendly, I studied a little bit and gave up, I do not quite understand how to modify, I want to be able to customize the high sensitivity area and inhibit the area, so that it will not be mistakenly touched!
2. whether you can specify the zoom sensitivity for different applications, windows gesture sensitivity of each application is a disaster!
3. The gesture to go back to the desktop in macos is really cool, use the five fingers to expand the gesture and go straight back to the desktop
These are some of the points that I have encountered when using the touchpad for windows where the experience doesn't add up, I hope this helps you in your subsequent product development, thanks!

**Comment by 2956694624** [comment]
https://learn.microsoft.com/zh-cn/windows-hardware/design/component-guidelines/touchpad-tuning-guidelines

**Comment by ClementGre** [comment]
Thank you for these improvement ideas. As this is not directly related to three finger drag, I don’t plan to add these features to the app soon, but maybe one day.
Thank’s!
