### ISSUE TITLE
Single contact mode switches to false leading the app not to work

### ISSUE THREAD

**Issue by knights1337** [ClementGre/ThreeFingerDragOnWindows#52]
Hi ClementGre,

I love this software, it's great. Recently, after I updated to v.2.0.3.0, I found a bug. At first I run the software, it work well. The main windows is as below, it can identify each fingers position.
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/55b01bd0-1038-4e01-98b4-28a1260bb2d2)

But after it ran for a period of time I found it didn't work. I found when my fingers touched the touchpad, it only identified one finger, and the single contact mode became false.
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/043bda1d-1d44-4ebe-afb7-efcc68fdf6cd)

The settings are:
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/f8f9729c-f3e1-4c86-ae0c-e8a8fd1e97ca)
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/e623e7dd-a079-4fbf-8fa7-ba5283311530)
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/f08d35d0-6980-45b3-a247-0fffc7798f98)
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/b0eb6c62-ff94-445e-b585-8fc9e0cf5f55)
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/e4cc9f7b-eebe-45bf-ac3d-a7bd96a03b71)
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/998aaf13-ffc1-4daf-a418-c85a0118c652)

The log is below:
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/ClementGre/ThreeFingerDragOnWindows/files/15087069/Logs_ThreeFingerDragOnWindows.txt)

Could you please help me to check the bug?

Thanks.

**Comment by bozwellox** [comment]
I'm also having this problem and can reproduce it (i.e. all three fingers show as inputs to start with, but after some time it only shows input from one). On Windows 11 also.

**Comment by ClementGre** [comment]
Hi, sorry for the late response.
The version 2.0.3 of TFDOW introduced the single contact mode detection to prevent issues on touchpads that sends empty contacts lists among normal contacts lists.
But when an empty contact list is detected, the app switches to the multi contact mode which prevents the app to work properly on touchpads that sends single contact lists.
I couldn’t see any empty contact list on your logs, but if you can catch an empty contact list in the logs (when the app starts to disfunction, when Single contact mode switches to False), it would confirm this.

I patched the bug in the source code and the issue should then be fixed for the next release.

If you restart the app, Single contact mode will be switched back to True.
Meanwhile, can uninstall the v2.0.3 and install the v2.0.2 from GitHub.

**Comment by knights1337** [comment]
> Hi, sorry for the late response. The version 2.0.3 of TFDOW introduced the single contact mode detection to prevent issues on touchpads that sends empty contacts lists among normal contacts lists. But when an empty contact list is detected, the app switches to the multi contact mode which prevents the app to work properly on touchpads that sends single contact lists. I couldn’t see any empty contact list on your logs, but if you can catch an empty contact list in the logs (when the app starts to disfunction, when Single contact mode switches to False), it would confirm this.
> 
> I patched the bug in the source code and the issue should then be fixed for the next release.
> 
> If you restart the app, Single contact mode will be switched back to True. Meanwhile, can uninstall the v2.0.3 and install the v2.0.2 from GitHub.


Thanks. Yes, I tried v2.0.2 and v2.0.1, both of those two versions work well and I didn't encounter this issue.

Thank you again :  )
