### ISSUE TITLE
Software often malfunctions on windows11 to the point of being unusable

### ISSUE THREAD

**Issue by wozaibeijizhuxueya** [ClementGre/ThreeFingerDragOnWindows#53]
The software can be used normally each time it is started, it stops running after a few minutes, it can run again after restart, and then it fails again after a while, the system of windows11

**Comment by ClementGre** [comment]
Have you noticed that when the app is getting inactive, single contact mode switches to false, then, only one contact is reported, even if you use multiple fingers?

![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/56594712/043bda1d-1d44-4ebe-afb7-efcc68fdf6cd)

I think this might be a duplicate of #52.
