### ISSUE TITLE
I can't use it with my hp notebook.

### ISSUE THREAD

**Issue by Ciagd** [ClementGre/ThreeFingerDragOnWindows#54]
It sometimes doesn't work in my Hp notebook, The exact model is 450 G8，plz... what can i do with this issue

**Comment by Ciagd** [comment]
and this is my touchpad settings.
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/36184541/3cbebd1d-8e8c-4338-980e-da14ffc772b7)

**Comment by Ciagd** [comment]
and the app settings
![image](https://github.com/ClementGre/ThreeFingerDragOnWindows/assets/36184541/25a798a8-274c-489e-9794-64861abb0570)

**Comment by ClementGre** [comment]
Do you think that this is a duplicate of #52 ?

**Comment by Ciagd** [comment]
> Do you think that this is a duplicate of #52 ?

yeah, Our problem are similar. Thank you and I'll try to use the version 2.0.2
