### ISSUE TITLE
Issue for version 2.0.3.0, sometimes can not use the function

### ISSUE THREAD

**Issue by nvansu** [ClementGre/ThreeFingerDragOnWindows#55]
the newest version of ThreeFingerDragOnWindows 2.0.3.0 caused a problem:
Sometimes I can not use the function. i have to restart the app. but a few times it can not drag with three figures again, although i set up do nothing the the setting of window according.
Please fix it. now, i must return to the version 2.0.2.0. so sad !

**Comment by ClementGre** [comment]
Do you think that this is a duplicate of #52 ?
