### ISSUE TITLE
Feature Request: Pick which mouse button is held down during the drag

### ISSUE THREAD

**Issue by brettlhartt** [ClementGre/ThreeFingerDragOnWindows#58]
When using certain CAD software, it is convenient to click and drag the MMB for certain commands. It appears this app will do exactly what I would like, but it only emulates the long-click of the left mouse button. If it could instead emulate the MMB, that would be very helpful.

**Comment by ClementGre** [comment]
Good idea, this is a really simple feature to add. I will probably add it in the next release.

**Comment by ClementGre** [comment]
I added this option in the app and it will be available in the next release in a few days. Thank you for the idea!
