### ISSUE TITLE
Delay before click release does't work properly

### ISSUE THREAD

**Issue by L1nktus** [ClementGre/ThreeFingerDragOnWindows#59]
It seems to happen when i release my fingers realy quick or 2 fingers at the same time, the click releases instantly.

**Comment by ClementGre** [comment]
Can you upload your log file? Generate it in the Other Settings tab, you can also watch the time on your computer and remove the lines that are before/after the drag issue for me to clearly see only the related logs.

**Comment by L1nktus** [comment]
> Can you upload your log file? Generate it in the Other Settings tab, you can also watch the time on your computer and remove the lines that are before/after the drag issue for me to clearly see only the related logs.

[Logs_ThreeFingerDragOnWindows.txt](https://github.com/ClementGre/ThreeFingerDragOnWindows/files/15373330/Logs_ThreeFingerDragOnWindows.txt)

Thanks for replying! Here are related logs.

**Comment by ClementGre** [comment]
According to your logs, the release is due to the fact that the app detected that only one finger was present on the touchpad and provoked the cursor to move more than 10 pixels. Maybe I should put the move threshold as an option in the settings cause it can vary in function of screen DPI and touchpad hardware.

**Comment by L1nktus** [comment]
> According to your logs, the release is due to the fact that the app detected that only one finger was present on the touchpad and provoked the cursor to move more than 10 pixels. Maybe I should put the move threshold as an option in the settings cause it can vary in function of screen DPI and touchpad hardware.

got it,sometimes it just releases randomly， thanks for replying!

**Comment by ClementGre** [comment]
But is never releases unless you releases your fingers right?

**Comment by L1nktus** [comment]
> But is never releases unless you releases your fingers right?

oh of course, generally speaking it's perfect, jumpy movement also doesn't exist when i turn off the accelerate.

**Comment by ClementGre** [comment]
If you think that this is still a bug that should be fixed, you can keep the issue opened, otherwise I won't work on it.

**Comment by L1nktus** [comment]
> If you think that this is still a bug that should be fixed, you can keep the issue opened, otherwise I won't work on it.

oh sorry, then I'll keep it opened

**Comment by L1nktus** [comment]
perfect solution by version 2.0.6.0, thank you!!!
