### ISSUE TITLE
Can't  detected touchpad on windows 10 installed on Mac Pro by Mac's Boot Camp Assistant  

### ISSUE THREAD

**Issue by TigerPhenix** [ClementGre/ThreeFingerDragOnWindows#60]
this may not be a bug ,but a feature , so it will supposed to be a surprise  if  get it to work,thanks very much .

**Comment by ClementGre** [comment]
Does Windows recognize the trackpad as a Windows Precision Touchpad (all gestures are available)?
If it does not, you might need to install the proper driver, see #28.

Anyway, if you are using an apple trackpad on windows, you might benefit from using another app that supports natively the apple magic trackpad, such as Trackpad++ (http://trackpad.forbootcamp.org/).

**Comment by TigerPhenix** [comment]
> Does Windows recognize the trackpad as a Windows Precision Touchpad (all gestures are available)? If it does not, you might need to install the proper driver, see #28.
> 
> Anyway, if you are using an apple trackpad on windows, you might benefit from using another app that supports natively the apple magic trackpad, such as Trackpad++ (http://trackpad.forbootcamp.org/).

Now the software can recognize the trackpad correctly  after I upgrade mac's  bootcamp control panel to version 6.1.0, so this issue can be closed  , thanks .

**Comment by tejasraman** [comment]
If someone finds this issue later, you can update Bootcamp to 6.1.0 to fix this only if you're on a 2018 or later Mac. Older Macs must use @imbusho 's precision touchpad Mac driver for Windows.
