### ISSUE TITLE
[Feature Request] "Alt-Drag" style window movement

### ISSUE THREAD

**Issue by Blaiziuss** [ClementGre/ThreeFingerDragOnWindows#65]
A unix feature where by holding Alt a subsequent left-click will allow the window to be moved relative to the mouse position, rather than clicking the title-bar.

Currently ThreeFingerDrag requires the title bar to be focused for the gesture to work, I believe alt-drag functionality (using only 3 fingers with no alt key) would be an indispensable addition to the convenience of the trackpad drag feature. Perhaps as an alternative to the current implementation if the two don't play nice.

[An example of the feature in use: Youtube](https://www.youtube.com/watch?v=rtN3giQs2Uo&t=77s)

[Original Alt-Drag for Windows application: Github](https://github.com/stefansundin/altdrag/releases), repo abandoned since 2015-08-23.

**Comment by ClementGre** [comment]
Hi, ThreeFingerDragOnWindows actually sends mouse press events to Windows. It does not actually "move windows" or "select text", but it just presses a button while three fingers are down.

Then developing an Alt-Drag feature, even if it could be integrated into TFDOW, would have no common logic with the ThreeFingerDrag feature.

I will close this issue as it is not planned for now.
