### ISSUE TITLE
Not working win 10

### ISSUE THREAD

**Issue by 1Erge** [ClementGre/ThreeFingerDragOnWindows#67]
Hi, app is not working (win 10 22H2) , these are my settings and log file. What can I do about it?
I tried installing early versions of the app and they didn't work either
![1](https://github.com/user-attachments/assets/3875e949-a68c-41e5-957c-a2a441b961e0)
![2](https://github.com/user-attachments/assets/f0b8c5a6-5abe-463b-80a1-b3f1453ff7ed)
![3](https://github.com/user-attachments/assets/c6b16a6c-dba5-474e-bc1c-273ae792928d)
![4](https://github.com/user-attachments/assets/0537d8c2-987f-48d1-b38b-602d393a75d1)
![5](https://github.com/user-attachments/assets/0b68a4be-fe7c-4c46-9446-bf3bd5782069)
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/user-attachments/files/16401880/Logs_ThreeFingerDragOnWindows.txt)

**Comment by ClementGre** [comment]
Hi, what is not working exactly? In your log file, the app is logging that it does moves the cursor and everything seems to work correctly from the logs point of view.

- Can you check if the cursor is correctly moving by raising the Mouse speed.
- Can you check if the left click is correctly pressed by dragging on a focusable element, or by switching the mouse button to Right and checking if a context menu appears at the end of the drag.
- Do you have an antivirus enabled? If yes, can you try to disable it?
