### ISSUE TITLE
Drag not working

### ISSUE THREAD

**Issue by aanganes79** [ClementGre/ThreeFingerDragOnWindows#70]
Hi! I've downloaded the latest version of the app and can't seem to get it to work. In the logs (attached a sample) it looks like it's correctly registering when 3 fingers are down, but it doesn't trigger the drag action. 

I am using an external trackpad - would that be an issue? I've tried with both an Apple Magic Trackpad (which I expected to not work well on Windows anyway) and with a brand new ProtoArc T1Plus touchpad which is designed for Windows. 
[Logs_ThreeFingerDragOnWindows.txt](https://github.com/user-attachments/files/17170987/Logs_ThreeFingerDragOnWindows.txt)

I've followed the readme on how to configure the settings within Windows. Thanks!

**Comment by ClementGre** [comment]
In your log file, the cursor did moved, see line 559 to 1042, and line 5626 to 5933, logged as ``[18:15:58.505]     MOVING, (x, y) = (-2, 3)``,

Maybe you can try to raise the mouse speed in the app settings, but your cursor should move as the app logs it. Maybe try to run the app as administrator.

About the Magic Trackpad, it should work well, and I actually use myself a Magic Trackpad to develop this app. Have you installed the Magic Trackpad driver for Windows Precision Touchpad (see https://github.com/imbushuo/mac-precision-touchpad) ?

**Comment by ClementGre** [comment]
Hi @aanganes79, thank you for your screenshots.
It seems that you selected ``None`` for the setting "Mouse button to be hold while dragging".
Then, even if everything works fine in your log file, your cursor is never moved.
Changing this setting from None to Left button should fix your issue!

**Comment by aanganes79** [comment]
Oh, that completely fixed my issue, thank you! I didn't understand what that setting did. This works great now, thanks so much! This was my biggest hurdle trying to switch over to Windows and makes things so much better :-) Appreciate your work!
