### ISSUE TITLE
Feature Request: Move Window with Three Fingers from Anywhere

### ISSUE THREAD

**Issue by Gwen0x4c3** [ClementGre/ThreeFingerDragOnWindows#72]
Hi, your program is really great and very convenient! I was wondering if it would be possible to move the window **from anywhere within it, rather than only from the title bar**. I've never used a Mac before, and I rarely use three fingers to select text. I think it would be  useful if there is a checkbox to enable/disable this feature, replacing the text selecting function depending on the user's preference.
Anyway, this is just my suggestion. If it's feasible, I would love to see this feature in the future!
Thanks for your hard work!

**Comment by ClementGre** [comment]
Hi,
TFDOW does nothing more than emulate a mouse click when the gesture is detected on the touchpad. It is not using any other API than the mouse API. It would then require some work to add this feature.

I suggest you look at [AltSnap](https://github.com/RamonUnch/AltSnap) which allows you to move a window by dragging it anywhere pressing the Alt key at the same time. With AltSnap, you just have to press Alt while dragging with three fingers to achieve your desired behaviour!

**Comment by Gwen0x4c3** [comment]
Thank you so much! After trying the three-finger text selection, I’ve found it to be extremely useful! 😂 If I’m the only one interested in this feature, feel free to ignore it. 😂 Maybe there wont be anyone else who wants such a valuable feature to be replaced. Your program is awesome—thanks again! 😀
